FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.23
COPY plugins/elasticsearch-analysis-ik-6.8.23 /usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-6.8.23
COPY plugins/elasticsearch-analysis-pinyin-6.8.23 /usr/share/elasticsearch/plugins/elasticsearch-analysis-pinyin-6.8.23
